# Generated by Django 4.1.7 on 2023-03-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('codigoDelActivo', models.CharField(max_length=200)),
                ('tipoDeLocalizacion', models.CharField(max_length=200)),
                ('clasificacion1', models.CharField(max_length=200)),
                ('clasificacion2', models.CharField(max_length=200)),
                ('centroDeCosto', models.CharField(max_length=200)),
                ('prioridad', models.CharField(max_length=200)),
                ('esParteDe', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
