# Generated by Django 4.1.7 on 2023-03-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ubicaciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ubicaciones',
            new_name='Ubicacion',
        ),
    ]
