# Generated by Django 4.1.7 on 2023-03-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_activo_rename_centrodecosto_ubicacion_centrocosto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rrhh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('nominal', models.PositiveSmallIntegerField()),
                ('extra', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
