# Generated by Django 4.1.7 on 2023-03-21 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_causa_reporte_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='causa',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='titulo',
        ),
    ]
