# Generated by Django 4.1.7 on 2023-03-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_reporte_causa_remove_reporte_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activo',
            new_name='Equipo',
        ),
    ]
