# Generated by Django 4.1.7 on 2023-04-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_reporte_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='clase',
            field=models.CharField(default='averia', max_length=200),
            preserve_default=False,
        ),
    ]
